### PR TITLE
fixes #39 Create ISSUE_TEMPLATE

### LINKED ISSUE #39: Create an ISSUES_TEMPLATE
You can get an example of this [here](https://github.com/sendgrid/open-source-library-data-collector/blob/master/.github/ISSUES_TEMPLATE.md)

### PR DESCRIPTION
**Pull request by rishiraj824**
Closes #39

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=40) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=40) it.</sub>

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=40) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=40) it.</sub>

**Comment by thinkingserious** [comment]
Hello @rishiraj824,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by rishiraj824** [comment]
FIlled it up. Thanks. 💯

**Pull request merged**
