### PR TITLE
Add test for date range in License file

### LINKED ISSUE #50: Add a unittest to check the license.md file date range
The end year in the license file should be "this year" and this should be checked on every run of the tests. If the end year is no correct, fail the test.
example: 
> Copyright (c) 2012-2016 SendGrid, Inc.
It is 2017, so this should be:
> Copyright (c) 2012-2017 SendGrid, Inc.
and the  test should fail.
--done

### PR DESCRIPTION
**Pull request by anshuman73**
# Fixes #50

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds test via command line to check if the License file has a correct date range. Also allows for standalone current year - for example, only the year ```2017``` is also valid at the time of commit.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=52) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=52) it.</sub>

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=52) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=52) it.</sub>

**Comment by anshuman73** [comment]
#53 breaks this as of now. Updating.

**Comment by mbernier** [comment]
This is a really creative way to solve this problem. Thank you!!

**Comment by anshuman73** [comment]
Hahaha, thanks !
I figured a shell script was probably better than introducing a nodejs check :)

**Comment by thinkingserious** [comment]
@anshuman73

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by anshuman73** [comment]
Hey ! 
I filled out the form again. Hope it worked fine this time.

Sure, as Sendgrid customer, I'd love to help make improvements in the product I use :)

**Comment by thinkingserious** [comment]
Thank you @anshuman73!

**Comment by thinkingserious** [comment]
Hello @anshuman73,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
