### PR TITLE
Add email template validation to TravisCI

### LINKED ISSUE #18: Add email template validation to TravisCI
Is there a way to validate the email HTML inside of a TravisCI script? Maybe through an npm package or something else? 

Set up a travis.yml that will cause all of the files within sub directories of this repo to be validated for proper HTML.

### PR DESCRIPTION
**Pull request by njerig**
Resolves #18

### CODE REVIEW

**Comment by mbernier** [comment]
I noticed that node_modules ended up coming along with your PR. I updated our .gitignore to exclude node_modules from being committed. 

Can you please remove this directory from your branch?

**Comment by mbernier** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=21) it.</sub>

**Comment by njerig** [comment]
Just removed node_modules. Anything else?

**Comment by mbernier** [comment]
@njerig I just got travis set up on our side. My apologies for not having it ready to go!
Can you please add an empty line to the bottom of one of your files, so that the Travis build kicks off?

**Comment by thinkingserious** [comment]
Hello @njerig,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
