### PR TITLE
Added Change Log

### LINKED ISSUE #5: Add a CHANGELOG to this repo
Add a changelog that follows [this format](https://github.com/sendgrid/sendgrid-python/blob/master/CHANGELOG.md)
- add the date this repo was created as the first entry

### PR DESCRIPTION
**Pull request by jakecarr**
Resolved #5

### CODE REVIEW

**Comment by mbernier** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=8) it.</sub>

**Comment by mbernier** [comment]
@jakecarr Can you please sign the CLA? I would like to get this merged in!

**Comment by thinkingserious** [comment]
@jakecarr

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request closed without merging**
