### PR TITLE
Adds Admin created account template

### PR DESCRIPTION
**Pull request by kentonh**
Adds template for email sent to user for scenarios where Admin creates accounts and user should then create password to complete the creation process.

I hope this is useful to others, but we constantly use this for business apps where an admin creates the account for users, and the user needs to complete the creation/registration process by creating their own password.

Typically, this is done through the same or similar code as the "forgot password" function, with a one-time use link generated and emailed to the user.

This template welcomes the new user, informs them of the process, and directs them to the next steps.

### CODE REVIEW

**Comment by kentonh** [comment]
Augments #6

**Comment by mbernier** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=25) it.</sub>

**Comment by mbernier** [comment]
@two24studios can you please give this a once over and merge it in?

**Comment by two24studios** [comment]
@kentonh @mbernier Thanks for adding this, but I don't see how this template any different from the `welcome.html` email template besides the text and filename?

**Comment by thinkingserious** [comment]
Hello @kentonh,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by kentonh** [comment]
Hey @two24studios,

This is a combination of the Welcome email template with the Reset Password template, with some extra copy. 

My team uses a template like this for apps where a manager needs to create the accounts of all the users, typically during a new hire or on boarding process.

**Pull request merged**
