### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by allan-pires**
Creates a pull request template (issue https://github.com/sendgrid/email-templates/issues/35)

Here is a preview of the template:

> 
> ## Story
> External link to story here.
> 
> ## Description
> Describe your changes here.
> 
> ## Tasks
> - [x] Feature 1 
> - [x] Feature 2
> - [ ] Feature 3
> 
> ## :warning:  Warning :warning: 
> Write down warnings here.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=38) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=38) it.</sub>

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=38) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/email-templates?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/email-templates?pullRequest=38) it.</sub>

**Comment by mbernier** [comment]
We had #37 just merged, can you look at that and merge the two versions? I really like what you did here.

**Comment by thinkingserious** [comment]
Hello @doisLan,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
